version: "3"

services:
  web:
    build: .
    image: django-finance-api
    command: python manage.py runserver 0.0.0.0:5000
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-notasecretatall}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-yes}
    volumes:
      - .:/app
    ports:
      - "5000:5000"
