# Generated by Django 4.1 on 2022-08-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("A", "Alimentação"),
                    ("I", "Imprevistos"),
                    ("E", "Educação"),
                    ("L", "Lazer"),
                    ("S", "Saúde"),
                    ("M", "Moradia"),
                    ("T", "Transporte"),
                    ("O", "Outras"),
                ],
                default="O",
                max_length=1,
            ),
        ),
    ]
